// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Mapsui;
using Mapsui.Tiling;
using Mapsui.UI.iOS;
using UIKit;

namespace iOSMapsuiTest
{
	public partial class MainViewController : UIViewController
	{
		public MainViewController() : base()
		{
		}
		public MainViewController(IntPtr handle) : base(handle)
		{
			MapControl.UseGPU = true;
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			var mapControl = new MapControl(View.Bounds);
			var map = new Map();
			map.Layers.Add(OpenStreetMap.CreateTileLayer());
			mapControl.Map = map;
			View = mapControl;
		}
	}
}
